Debug: bool
AppKey: string

AdminLogin: string
AdminPassword: string

AwsKey: string
AwsSecret: string
AwsRegion: string

DatabaseDriver: sqlight3
DatabaseDSN: ./database.db

NoReplyEmail: string
ReplyEmail: string

MaxFileUploadSizeMb: 10

Port: :8081